name: codegraph
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - jupyter=1.0.*
  - matplotlib=3.6.*
  - nbconvert=7.2.*
  - nbconvert-webpdf=7.2.*
  - numpy=1.23.*
  - pandas=1.5.*
  - pip=22.3.*
  - opentsne=1.0.* # to visualize node embeddings in 2D (t-SNE dimensionality reduction)
  - pip:
      - monotonic==1.*
      - wordcloud==1.9.*
      - neo4j==5.11.*