name: codegraph
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - jupyter=1.0.*
  - matplotlib=3.7.*
  - nbconvert=7.3.*
  - nbconvert-webpdf=7.3.*
  - numpy=1.24.*
  - pandas=2.0.*
  - pip=23.1.*
  - pip:
      - monotonic==1.6
      - py2neo==2021.2.*
      - wordcloud==1.9.*