name: codegraph
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - jupyter=1.0.*
  - matplotlib=3.6.*
  - nbconvert=7.2.*
  - nbconvert-webpdf=7.2.*
  - numpy=1.23.*
  - pandas=1.5.*
  - pip=22.3.*
  - scikit-learn=1.3.* # NodeEmbeddings.ipynb uses sklearn.manifold.TSNE 
  - pip:
      - monotonic==1.*
      - wordcloud==1.9.*
      - neo4j==5.11.*