name: codegraph
channels:
  - conda-forge/label/python_rc # Needed on Mac since Python >= 3.12
  - plotly
  - conda-forge
dependencies:
  - python=3.12.*
  - _python_rc=* # Needed on Mac since Python >= 3.12
  - jupyter=1.1.*
  - matplotlib=3.10.*
  - nbconvert=7.16.*
  - nbconvert-webpdf=7.16.*
  - numpy=1.26.*
  - pandas=2.2.*
  - pip=25.0.*
  - setuptools=75.8.* # opentsne uses sklearn.base uses joblib uses distutils missing in Python >= 12 (TODO use native openTSNE?) 
  - typing-extensions=4.12.* # Also needed for opentsne and Python >= 3.12
  - opentsne=1.0.* # to visualize node embeddings in 2D (t-SNE dimensionality reduction)
  - wordcloud=1.9.*
  - monotonic=1.*
  - plotly=6.0.*
  - python-kaleido=0.2.* # To render plotly plots. Static image export for web-based visualization libraries.
  - pip:
      - neo4j==5.23.*