#!/usr/bin/env bash

# Generates "CSV_REPORTS.md" containing a reference to all CSV cypher query reports in this directory and its subdirectories.

# Note: This script was generated by Chat-GPT after some messages back and forth:
# https://chat.openai.com/share/0bd3cde7-32d0-460d-830c-79b7d00a2492

# Output Markdown file name
output_file="CSV_REPORTS.md"

# Function to count rows in a CSV file
count_rows() {
  wc -l < "$1"
}

# Function to extract the source query name from CSV header
get_source_query() {
  header=$(head -n 1 "$1")
  source_query=$(echo "$header" | sed -n 's/.*Source Cypher File: \(.*\)"/\1/p')
  echo "$source_query"
}

# Create the Markdown header
{
  echo "# CSV Cypher Query Reports Reference"
  echo ""
  echo "This document serves as a reference for all CSV Cypher query reports in the current directory and its subdirectories. It provides a table listing each file, its corresponding analysis, the row count and the source query. This file was generated with the script [generateCsvReportsReference](./../scripts/documentation/generateCsvReportsReference.sh)."
  echo ""
  
  # Create the Markdown table header
  echo "| CSV File | Analysis | Number of Rows | Source Query |"
  echo "| -------- | -------- | -------------- | ------------ |"
} > "$output_file"

# Find and process CSV files
find . -type f -name "*.csv" | while IFS= read -r csv_file; do
  num_rows=$(count_rows "$csv_file")
  source_query=$(get_source_query "$csv_file")
  
  # Get the main directory name
  main_dir=$(dirname "$csv_file" | cut -d '/' -f 2)
  
  # Get the base name of the file
  base_name=$(basename "$csv_file")
  
  # Escape special characters for Markdown
  csv_link=$(echo "$csv_file" | sed 's/\[/\\[/g; s/\]/\\]/g')
  
  # Create a link to the source query
  source_query_link="./../cypher/$source_query"
  
  # Append a new row to the Markdown table
  echo "| [$base_name]($csv_link) | $main_dir | $num_rows | [$source_query]($source_query_link) |" >> "$output_file"
done

echo "CSV table and header generated in $output_file"
