#!/usr/bin/env bash

# Generates a SCIP index for a TypeScript project using scip-typescript (via npx).
# Assumes Node.js 18+, project dependencies, and scip CLI are already installed.
# Produces index.scip (binary) and index.scip.json (JSON for the pipeline) in PROJECT_DIR.
# This script is meant to be executed within an analysis workspace directory (temp/<name-of-analysis>).
# See analyzeReactRouterScip.sh for a complete example with setup.

# Requires domains/scip-index-import/installScipCli.sh

# Fail on any error ("-e" = exit on first error, "-o pipefail" exit on errors within piped commands)
set -o errexit -o pipefail -o nounset
IFS=$'\n\t'

SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")

# Overrideable defaults
# TOOLS_DIRECTORY from analysis workspace, defaults to ./tools
TOOLS_DIRECTORY=${TOOLS_DIRECTORY:-"./tools"}
SCIP_BINARY=${SCIP_BINARY:-"${TOOLS_DIRECTORY}/scip-cli/scip"}

# Convert SCIP_BINARY to absolute path if relative
if [[ "${SCIP_BINARY}" != /* ]]; then
    SCIP_BINARY="$(cd "$(dirname "${SCIP_BINARY}")" && pwd)/$(basename "${SCIP_BINARY}")"
fi

function usage() {
    local exit_code="${1:-1}"
    echo "Usage: ${SCRIPT_NAME} <project-dir> [<scip-typescript index options>] [--help]"
    echo ""
    echo "Arguments:"
    echo "  project-dir   Path to TypeScript project with package.json and node_modules already installed"
    echo ""
    echo "Options:"
    echo "  Any extra arguments are forwarded to: scip-typescript index"
    echo "  e.g. --pnpm-workspaces, --yarn-workspaces"
    echo "  Note: --infer-tsconfig is always enabled to handle projects without tsconfig.json"
    echo ""
    echo "Environment variables:"
    echo "  SCIP_BINARY       Path to scip CLI binary (default: ./tools/scip-cli/scip)"
    echo "  TOOLS_DIRECTORY   Base tools directory (default: ./tools)"
    echo ""
    echo "Prerequisites (must be ready before calling this script):"
    echo "  Node.js 18+ (npx is used to run @sourcegraph/scip-typescript)"
    echo "  Project dependencies installed (npm install or pnpm install)"
    echo "  (scip-typescript will be fetched by npx if not in local node_modules)"
    echo "  scip CLI binary (install with: domains/scip-index-import/installScipCli.sh)"
    echo ""
    echo "Output files in <project-dir>:"
    echo "  index.scip      Binary SCIP index"
    echo "  index.scip.json JSON SCIP index (place in indices/ for the pipeline)"
    echo ""
    echo "Examples:"
    echo "  ${SCRIPT_NAME} ./source/react-router-7.13.1"
    echo "  ${SCRIPT_NAME} ./source/react-router-7.13.1 --pnpm-workspaces"
    exit "${exit_code}"
}

if [ "${1:-}" = "--help" ]; then
    usage 0
fi

if [ $# -lt 1 ]; then
    usage 1
fi

PROJECT_DIR="${1}"
shift

if [ ! -d "${PROJECT_DIR}" ]; then
    echo "${SCRIPT_NAME}: Error: Project directory '${PROJECT_DIR}' does not exist." >&2
    exit 1
fi

# Convert to absolute path to avoid issues with relative paths in function scope
PROJECT_DIR=$(cd "${PROJECT_DIR}" && pwd)

if [ ! -f "${PROJECT_DIR}/package.json" ]; then
    echo "${SCRIPT_NAME}: Error: No package.json found in '${PROJECT_DIR}'." >&2
    echo "${SCRIPT_NAME}: Provide a valid TypeScript/npm project directory." >&2
    exit 1
fi

function check_node() {
    if ! command -v node >/dev/null 2>&1; then
        echo "${SCRIPT_NAME}: Error: Node.js not found in PATH." >&2
        echo "${SCRIPT_NAME}: Install: brew install node (macOS) or https://nodejs.org" >&2
        exit 1
    fi
    local node_major
    node_major=$(node --version | sed 's/v//' | cut -d. -f1)
    if [ "${node_major}" -lt 18 ]; then
        echo "${SCRIPT_NAME}: Error: Node.js 18+ is required. Found: $(node --version)" >&2
        exit 1
    fi
    echo "${SCRIPT_NAME}: Node.js $(node --version) found."
}

function check_scip_cli() {
    if [ ! -x "${SCIP_BINARY}" ]; then
        echo "${SCRIPT_NAME}: Error: scip CLI not found at '${SCIP_BINARY}'." >&2
        echo "${SCRIPT_NAME}: Install it first: domains/scip-index-import/installScipCli.sh" >&2
        exit 1
    fi
    local version
    version=$("${SCIP_BINARY}" --version 2>&1 | head -1 || true)
    echo "${SCRIPT_NAME}: scip CLI found (${version})."
}

function generate_scip_index() {
    echo "${SCRIPT_NAME}: Running scip-typescript to generate index.scip..."
    cd "${PROJECT_DIR}"
    if ! npx --yes @sourcegraph/scip-typescript@v0.4.0 index --infer-tsconfig "${@}"; then
        echo "${SCRIPT_NAME}: Error: scip-typescript indexing failed." >&2
        exit 1
    fi
    if [ ! -f "${PROJECT_DIR}/index.scip" ]; then
        echo "${SCRIPT_NAME}: Error: index.scip was not generated by scip-typescript." >&2
        exit 1
    fi
    local size
    size=$(du -h "${PROJECT_DIR}/index.scip" | cut -f1)
    echo "${SCRIPT_NAME}: index.scip generated (${size})."
}

function convert_scip_to_json() {
    local json_output="${PROJECT_DIR}/index.scip.json"
    echo "${SCRIPT_NAME}: Converting index.scip → index.scip.json..."
    if ! "${SCIP_BINARY}" print --json "${PROJECT_DIR}/index.scip" > "${json_output}"; then
        echo "${SCRIPT_NAME}: Error: Failed to convert index.scip to JSON." >&2
        exit 1
    fi
    if ! jq empty "${json_output}" >/dev/null 2>&1; then
        echo "${SCRIPT_NAME}: Error: Generated index.scip.json is not valid JSON." >&2
        exit 1
    fi
    local size
    size=$(du -h "${json_output}" | cut -f1)
    echo "${SCRIPT_NAME}: index.scip.json generated (${size}) → ${json_output}"
}

check_node
check_scip_cli
generate_scip_index "${@}"
convert_scip_to_json
echo "${SCRIPT_NAME}: Done. Place '${PROJECT_DIR}/index.scip.json' in the 'indices/' directory before running analyze.sh."
