#!/usr/bin/env bash

# Generates "REPORTS.md" containing a reference to all Markdown files in this directory and its sub directories.
# This script was generated by Chat-GPT after some messages back and forth and then tuned manually.

# Markdown file name
markdown_file="REPORTS.md"

# Generate the Markdown table content
markdown_table="| File Name | Title |
|-----------|-------|
"

# Function to generate Markdown table for a given directory
generate_markdown_table() {
  local directory="$1"

  # Loop through all Markdown files in the directory
  local files=()
  while IFS= read -r -d '' file; do
    files+=("$file")
  done < <(find "$directory" -maxdepth 1 -type f -name "*.md" -print0)

  if [ "${#files[@]}" -gt 0 ]; then
    for file in "${files[@]}"; do
      # Get the title of the Markdown file
      title=$(awk -F"#" 'NR==2 {gsub(/^[[:blank:]]+|[[:blank:]]+$/, "", $2); print $2; exit}' "$file")

      # Add the file name and title to the table
      markdown_table+="| [$file]($file) | ${title//|/\\|} |\n"
    done
  fi
}

# Generate Markdown table for the current directory
generate_markdown_table "."

# Recursively generate Markdown table for all subdirectories
while IFS= read -r -d '' directory; do
  generate_markdown_table "$directory"
done < <(find . -type d -name "*" -not -path "./.*" -print0)

# Create a new Markdown file with the Markdown table
echo -e "# Markdown Reference\n\nThis document serves as a reference for all Markdown files in the current directory and its subdirectories. It provides a table listing each file name and its corresponding title as specified by the `#` header.\n\n$markdown_table" > "$markdown_file"
