#!/usr/bin/env bash

# Tests: scan all *.sh files (current directory including subdirectories)
# for occurrences of cypher and other filename references without paths and ensure a file with
# the referenced basename exists somewhere in the tree.

# Fail on any error
set -o errexit

# Fail if any command in a pipeline fails (not just the last one)
if set -o pipefail 2>/dev/null; then
  set -o pipefail
fi

SCRIPT_NAME="testCypherReferences.sh"
COLOR_ERROR='\033[0;31m'
COLOR_DE_EMPHASIZED='\033[0;90m'
COLOR_SUCCESSFUL="\033[0;32m"
COLOR_DEFAULT='\033[0m'

# Determine this scripts dir (POSIX-friendly)
SCRIPTS_DIR=${SCRIPTS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)}

tearDown() {
  rm -rf "${temporaryTestDirectory}"
}

successful() {
  echo -e "${COLOR_DE_EMPHASIZED}${SCRIPT_NAME}:${COLOR_DEFAULT} ${COLOR_SUCCESSFUL}✅ Tests finished successfully.${COLOR_DEFAULT}"
  tearDown
}

info() {
  local infoMessage="${1}"
  echo -e "${COLOR_DE_EMPHASIZED}${SCRIPT_NAME}:${COLOR_DEFAULT} ${infoMessage}"
}

fail() {
  local errorMessage="${1}"
  echo -e "${COLOR_DE_EMPHASIZED}${SCRIPT_NAME}: ${COLOR_ERROR}${errorMessage}${COLOR_DEFAULT}"
  tearDown
  return 1
}

printTestLogFileContent() {
  local logFileName="${temporaryTestDirectory}/${SCRIPT_NAME}-${reference_extension}.log"
  if [ -f "${logFileName}" ]; then
    local logFileContent
    logFileContent=$(cat "${logFileName}")
    # Remove common color codes for readability
    echo -e "${COLOR_DE_EMPHASIZED}${logFileContent}${COLOR_DEFAULT}"
  else
    echo -e "${COLOR_ERROR}No log file found at expected location: %s${COLOR_DEFAULT}" "${logFileName}"
  fi
}

find_missing_file_references() {
  # Capture stdout/stderr into a log file for this run
  reference_extension="$1"
  {
    missing_file="${temporaryTestDirectory}/missing_${reference_extension}_references.txt"
    : > "${missing_file}"

    # Collect all reference filenames without path present in the repo
    reference_filenames="${temporaryTestDirectory}/reference_${reference_extension}_filenames.txt"
    find . \
      \( -type d \( -name "temp" -o -name ".git" -o -name "node_modules" \) -prune \) -o \
      \( -type f -name "*.${reference_extension}" -print \) \
      2>/dev/null | sed 's#.*/##' > "${reference_filenames}"
    
    echo "pnpm-lock.yaml" >> "${reference_filenames}" # Ignore pnpm-lock file references by pretending it exists since it is not checked in but generated by users locally.

    # Iterate over all shell scripts
    find . \
      \( -type d \( -name "temp" -o -name ".git" -o -name "node_modules" \) -prune \) -o \
      \( -type f -name '*.sh' ! -name "test*" -print0 \) \
    | while IFS= read -r -d '' script_file; do
      # Skip this test file itself
      if [ "$(basename "${script_file}")" = "${SCRIPT_NAME}" ]; then
          continue
      fi

      # Use awk to extract all reference file name extension matches from non-comment lines
      awk -v reference_extension="${reference_extension}" '
      /^[[:space:]]*#/ { next }
      {
        line = $0
        pattern = "(/[^/[:space:]\"]+\\." reference_extension ")|(\"[^/[:space:]\"]+\\." reference_extension "\")"

        while (match(line, pattern)) {
          ref = substr(line, RSTART, RLENGTH)
          gsub(/^"|\"$/, "", ref)   # remove surrounding quotes
          gsub(/^\//, "", ref)      # remove leading slash
          
          if (ref !~ /\$/ && ref !~ /\*/) {
            print ref
          }
          line = substr(line, RSTART + RLENGTH)
        }
      }
      ' "${script_file}" | while IFS= read -r reference_file; do
        [ -z "${reference_file}" ] && continue
        reference_filename=$(basename "${reference_file}")
        if ! grep -Fx -- "${reference_filename}" "${reference_filenames}" >/dev/null 2>&1; then
          printf '%s\t%s\n' "${script_file#./}" "${reference_file}" >> "${missing_file}"
        fi
      done
    done
  } > "${temporaryTestDirectory}/${SCRIPT_NAME}-${reference_extension}.log" 2>&1

  if [ -s "${missing_file}" ]; then
      echo -e "${COLOR_DE_EMPHASIZED}${SCRIPT_NAME}:${COLOR_ERROR}     ERROR: Missing referenced ${reference_extension} files (by basename):${COLOR_DEFAULT}"
      awk -F"\t" '{ printf("  - In %s -> referenced %s\n", $1, $2) }' "${missing_file}"
      
      # Print content of reference_filenames for debugging purposes
      # echo -e "\n${COLOR_DE_EMPHASIZED}List of all ${reference_extension} files found in the repository (by basename):${COLOR_DEFAULT}"
      # cat "${reference_filenames}" | while IFS= read -r filename; do
      #   echo -e "  - ${filename}"
      # done
      # echo ""
      
      printTestLogFileContent
      fail "${test_case_number}.) ❌ Test failed. Missing referenced ${reference_extension} files found. See details above."
  fi
}

info "Starting tests...."

temporaryTestDirectory=$(mktemp -d 2>/dev/null || mktemp -d -t "temporaryTestDirectory_${SCRIPT_NAME}")
mkdir -p "${temporaryTestDirectory}"

# ------- Integration-style Test Case
test_case_number=1
info "${test_case_number}.) Scan all .sh files for '/...*.cypher' references and verify filenames exist."
find_missing_file_references "cypher"

# ------- Integration-style Test Case
test_case_number=2
info "${test_case_number}.) Scan all .sh files for '/...*.yaml' references and verify filenames exist."
find_missing_file_references "yaml"

successful
return 0
