name: Generate cypher reference documentation

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cypher' # Only run when cypher files changed
      - '.github/workflows/cypher-reference-documentation.yml' # or when this file was changed
  pull_request:
    branches:
      - main
    paths: 
      - '**/*.cypher' # Only run when cypher files changed
      - '.github/workflows/cypher-reference-documentation.yml' # or when this file was changed

jobs:
  reports:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Automated cypher reference document generation (CI)
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
  
    - name: Generate cypher reference document
      working-directory: cypher
      run: |
        ./../scripts/documentation/generateCypherReference.sh

    - name: Archive generated cypher reference document
      uses: actions/upload-artifact@v3
      with:
        name: cypher-reference-document
        path: ./cypher/CYPHER.md
        if-no-files-found: error
        retention-days: 5

    - name: Use git to detect changes in the regenerated document and set generated_document_changed
      run: git diff-index --quiet HEAD || echo "generated_document_changed=true" >> $GITHUB_ENV

    - name: Display generated_document_changed
      run: echo "generated_document_changed=${{ env.generated_document_changed}}"

    - name: Commit generated cypher reference document if there were changes
      # Only run when a pull request gets merged or a commit is pushed to the main branch.
      # And only run when the generated document changed to avoid an empty commit or an error while committing.
      if: github.event_name == 'push' && env.generated_document_changed
      run: |
        git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
        git config --global user.email 'joht@users.noreply.github.com'
        git pull
        git add ./cypher/CYPHER.md
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
